#!/usr/bin/env python3
"""Rebuild signup/ROSTER.md from the signup/lectureNN-*.md files.

Each sign-up file carries a small YAML-ish front matter block:

    ---
    name: Tong Li
    student_id: 20261201094
    email: litong@westlake.edu.cn
    github: tongli
    lecture: 9
    teammates: Name A, Name B
    ---

One student may appear in more than one lecture. The first teaching assignment is
required; every additional assignment is a volunteer registration for extra credit.

Stdlib only. Run from the repository root: python3 tools/build_roster.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SIGNUP = ROOT / "signup"

LECTURES = {
    3: ("2026-09-08", "Reaction networks, with the central dogma as the worked example"),
    4: ("2026-09-10", "Dynamics: local stability, phase portraits, bifurcations"),
    5: ("2026-09-15", "Stochastic dynamics: the master equation and Gillespie"),
    6: ("2026-09-17", "Timescale separation: singular perturbation, QSSA, telegraph model"),
    7: ("2026-09-22", "Equilibrium parts driven out of equilibrium"),
    8: ("2026-09-24", "The cell as a biomachine: binding and catalysis"),
    9: ("2026-09-29", "Multistability and oscillations"),
    10: ("2026-10-08", "The adaptation biomachine"),
    11: ("2026-10-13", "Analysis of binding and catalysis via reaction-order structure"),
    12: ("2026-10-15", "The computation biomachine"),
    13: ("2026-10-20", "The metabolic biomachine"),
    14: ("2026-10-22", "The growth biomachine"),
    15: ("2026-10-27", "Introduction to protein design"),
    16: ("2026-10-29", "Foundational virtual cells that are fully mechanistic"),
}
CAP = 3


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"\s*---\s*\n(.*?)\n---\s*\n?", text, re.S)
    if not m:
        return None
    out = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            out[k.strip().lower()] = v.strip()
    return out


def main():
    entries = []
    bad = []
    for p in sorted(SIGNUP.glob("lecture*.md")):
        if p.name == "TEMPLATE.md":
            continue
        d = parse(p)
        if not d:
            bad.append((p.name, "no front matter block"))
            continue
        try:
            n = int(str(d.get("lecture", "")).strip())
        except ValueError:
            bad.append((p.name, "lecture is not a number"))
            continue
        if n not in LECTURES:
            bad.append((p.name, f"lecture {n} is not a student-taught lecture (3-16)"))
            continue
        name = d.get("name") or p.stem.split("-", 1)[-1]
        if d.get("name_zh"):
            name = f"{name} ({d['name_zh']})"
        github = d.get("github", "").strip().lstrip("@")
        github_key = github.lower()
        student_id = d.get("student_id", "").strip().lower()
        email = d.get("email", "").strip().lower()
        identity = ("github", github_key) if github_key else (
            ("student_id", student_id) if student_id else (
                ("email", email) if email else ("file", p.name)
            )
        )
        entries.append((n, name, github, p.name, identity))

    by_lecture = {n: [] for n in LECTURES}
    by_person = {}
    for n, name, gh, fn, identity in sorted(entries):
        by_lecture[n].append((name, gh, fn))
        by_person.setdefault(identity, []).append((n, name, gh, fn))

    student_count = len(by_person)
    assignment_count = len(entries)
    extra_count = assignment_count - student_count
    student_verb = "has" if student_count == 1 else "have"

    lines = [
        "# Teaching roster",
        "",
        "*Rebuilt automatically on every merge to `main` by `.github/workflows/roster.yml`.*",
        "*Do not edit this file by hand; edit your own `signup/lectureNN-yourname.md` instead.*",
        "",
        f"**{student_count} student{'s' if student_count != 1 else ''} {student_verb} signed up "
        f"for {assignment_count} teaching assignment{'s' if assignment_count != 1 else ''}.**",
        f"Each enrolled student must teach at least once. A lecture may have 1 to {CAP} students; "
        "Fangzhou Xiao teaches it if no student claims it.",
        "Completing each additional lecture is voluntary and earns extra credit.",
        "",
        "| # | Date | Topic | Team | Student places |",
        "|---|---|---|---|---|",
    ]
    for n, (date, topic) in LECTURES.items():
        team = by_lecture[n]
        who = ", ".join(f"{name}" + (f" (@{gh})" if gh else "") for name, gh, _ in team) or "_open_"
        left = CAP - len(team)
        if len(team) == 0:
            room = f"**{left} open; lecturer covers if unclaimed**"
        elif left > 0:
            room = f"{left} open"
        else:
            room = "full"
        lines.append(f"| {n} | {date} | {topic} | {who} | {room} |")

    if extra_count:
        lines += ["", "## Volunteer extra-credit assignments", ""]
        for assignments in sorted(
            (items for items in by_person.values() if len(items) > 1),
            key=lambda items: (items[0][1].lower(), items[0][2]),
        ):
            lectures = ", ".join(str(item[0]) for item in assignments)
            name, gh = assignments[0][1], assignments[0][2]
            who = name + (f" (@{gh})" if gh else "")
            extra = len(assignments) - 1
            lines.append(
                f"- {who}: lectures {lectures}; {extra} additional "
                f"assignment{'s' if extra != 1 else ''} registered for extra credit."
            )

    if bad:
        lines += ["", "## Files that could not be read", ""]
        lines += [f"- `signup/{fn}`: {why}" for fn, why in bad]

    lines += [
        "",
        "---",
        "",
        "To sign up, or to volunteer for another lecture: fork this repository, copy `signup/TEMPLATE.md` to "
        "`signup/lectureNN-yourname.md`, fill it in, and open a pull request. "
        "Use one file and one pull request per lecture. It merges automatically once the filename and contents check out.",
        "",
    ]
    (SIGNUP / "ROSTER.md").write_text("\n".join(lines), encoding="utf-8")
    print(
        f"roster rebuilt: {student_count} students, {assignment_count} assignments, "
        f"{len(bad)} unreadable"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
